version: "3.5"
services:
  proxy:
    build: ./env/waterfall
    volumes:
      - "./servers/proxy:/waterfall"
  auth:
    build: 
      context: ./env/paper
      args:
        version: "1.16"
    environment:
      eula: "true"
    volumes:
      - "./servers/auth:/paper"
    
    
    
